

class Const:
    """const params, do not edit this file"""
    REST_API = 'http://127.0.0.1:3000'
    REST_USER = 'user'
    REST_PWD = 'password'
    HRP = 'test'  # human-readable-part
    DATABASE_PATH = 'pool.db'
    HOST_NAME = 'localhost'


__all__ = [
    "Const",
]
